apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: whoami
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "1m"
spec:
  type: GitHubPullRequest
  url: https://github.com/littleboycoding/flux-operator-101
  filter:
    labels:
      - "deploy/flux-preview"
